[tools]
bun = "latest"
zola = "latest"

[vars]
port = "1111"

[tasks]
check = "zola check"
build = "zola build"
validate = "uv run docs/validate_providers.py"

[tasks.serve]
depends = ["build"]
run = """
#!/usr/bin/env bash
if nc -z localhost {{vars.port}}; then
  echo "zola is already serving"
else
  zola serve --port {{vars.port}} &
fi
"""

[tasks.stop]
run = """
#!/usr/bin/env bash
if nc -z localhost {{vars.port}}; then
  killall zola
else
  echo "zola is not running"
fi
"""

[tasks.a11y]
description = "Accessibility tests"
depends = ["serve"]
run = """
bunx browser-driver-manager@2.0.1 install chrome
bunx @axe-core/cli@4.11.1 http://localhost:{{vars.port}}/ \
  http://localhost:{{vars.port}}/providers/ \
  http://localhost:{{vars.port}}/providers/scaleway/ \
  http://localhost:{{vars.port}}/compare.html?providers=aws,google-cloud,microsoft-azure --exit
EXIT_CODE=$?
exit $EXIT_CODE
"""

[tasks.test]
description = "Run full tests"
depends = ["validate", "check", "a11y"]

