name: Build and deploy Zola website
on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Build Zola + upload Pages artifact
        uses: getzola/github-pages@435a833fd3f1edcb28d70576c89e30a6365cd8f7
        with:
          zola_version: v0.22.1
          check_links: true
          check_flags: "--skip-external-links"

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
