---
name: Daily Tests with Energy Measurement
run-name: Scheduled - DEV Branch
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0
        with:
          task: start-measurement
        continue-on-error: true

      - name: 'Checkout repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: 'dev'
          submodules: 'true'

      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0
        with:
          task: get-measurement
          label: 'repo checkout'
        continue-on-error: true

      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: "3.14"
          activate-environment: true
          enable-cache: auto

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Setup Python Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0
        with:
          task: get-measurement
          label: 'python setup'
        continue-on-error: true

      - name: Run Tests
        shell: bash
        run: pytest

      - name: Tests measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0
        with:
          task: get-measurement
          label: 'pytest'
        continue-on-error: true

      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0
        with:
          task: display-results
        continue-on-error: true
