name: Lighthouse CI
on: [push]
permissions: {}
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Lighthouse analysis
        run: bunx @lhci/cli@0.15.x autorun

